version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose the frontend's port
    command: ["npm", "start"]
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: "${REACT_APP_BACKEND_URL}"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}" # Map backend's port dynamically
    command: ["node", "server.js"]
    environment:
      PORT: "${PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: secure_login-db
    ports:
      - "${DB_PORT}:5432" # Map the DB port dynamically
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
