import React, { useState, useEffect } from "react";
import axios from "axios";
import { TextField, Button, Container, Typography, Alert, Grid, Divider } from "@mui/material";

const MFASetup = ({ email }) => {
  const [qrCode, setQrCode] = useState("");
  const [otp, setOtp] = useState("");
  const [mfaMessage, setMfaMessage] = useState("");

  useEffect(() => {
    const generateQRCode = async () => {
      try {
        const response = await axios.post("http://localhost:5005/api/mfa/generate", { email });
        if (response.data.qrCode) {
          setQrCode(response.data.qrCode);
        }
      } catch (error) {
        console.error("Error generating QR code:", error);
      }
    };

    generateQRCode();
  }, [email]);

  const handleVerifyMFA = async () => {
    try {
      const response = await axios.post("http://localhost:5005/api/mfa/verify", { email, otp });

      if (response.data.message === "MFA verified successfully.") {
        setMfaMessage("MFA verified successfully.");
      } else {
        setMfaMessage("Failed to verify MFA. Please try again.");
      }
    } catch (error) {
      console.error("Error verifying MFA:", error);
      setMfaMessage("Failed to verify MFA. Please try again.");
    }
  };

  return (
    <Container maxWidth="sm" style={{ marginTop: "20px" }}>
      <Typography variant="h5" component="h2" gutterBottom>
        Set Up Multi-Factor Authentication (MFA)
      </Typography>
      <Typography variant="body1" gutterBottom>
        Multi-Factor Authentication (MFA) enhances your account security by requiring an additional step to verify your identity. Follow these steps:
      </Typography>
      <ol>
        <li>Download the <b>Microsoft Authenticator</b> app from the App Store or Google Play Store.</li>
        <li>Open the app and select "Add Account" or "+" to scan a QR code.</li>
        <li>Scan the QR code displayed below using the app.</li>
        <li>Enter the OTP (One-Time Password) generated by the app to verify your setup.</li>
      </ol>

      {qrCode && (
        <img
          src={qrCode}
          alt="MFA QR Code"
          style={{ margin: "20px auto", width: "200px", display: "block" }}
        />
      )}

      <Typography variant="body1" gutterBottom>
        Need help? Watch this video tutorial on setting up MFA:
      </Typography>
      <div style={{ textAlign: "center", marginBottom: "20px" }}>
        <iframe
          width="100%"
          height="315"
          src="https://www.youtube.com/embed/UwXTtKdyE7g"
          title="How to Set Up Microsoft Authenticator"
          frameBorder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
        ></iframe>
      </div>

      <TextField
        label="Enter OTP"
        fullWidth
        value={otp}
        onChange={(e) => setOtp(e.target.value)}
        style={{ margin: "20px 0" }}
      />
      <Button variant="contained" color="secondary" onClick={handleVerifyMFA} fullWidth>
        Verify OTP
      </Button>

      {mfaMessage && (
        <Alert severity={mfaMessage === "MFA verified successfully." ? "success" : "error"} style={{ marginTop: "20px" }}>
          {mfaMessage}
        </Alert>
      )}
    </Container>
  );
};

export default MFASetup;
